#!/usr/bin/python
#Yum

import pyautogui
pyautogui.PAUSE = 1
pyautogui.FAILSAFE = True #When fail-safe mode is True, moving the mouse to the upper-left will raise 
#a pyautogui.FailSafeException that can abort your program.

#Magic
pyautogui.click(pyautogui.locateOnScreen((pyautogui.center('home_butt.png')))
pyautogui.click(pyautogui.locateOnScreen((pyautogui.center('home_search.png')))
