#!/bin/bash
#Yum

sudo apt-get install python3-dev
sudo apt-get install python3-pip
sudo pip3 install python3-xlib
sudo apt-get install scrot
sudo apt-get install python3-tk
sudo apt-get install python3-xlib
pip3 install pyautogui
  pyautogui.FAILSAFE = True
 
 #Updates
 pyautogui.moveTo(25, 61)
 pyautogui.click()
 pyautogui.typewrite('software updater\n', interval=secs_between_keys)
 pyautogui.moveTo(159, 160)
 pyautogui.click()
